export const allergies = [
    "aceite",
    "arroz",
    "avena",
    "azúcar",
    "café",
    "carne de cerdo",
    "res",
    "crema",
    "cuajada",
    "frijol",
    "frutas",
    "guineo",
    "leche",
    "maíz",
    "malanga",
    "miel",
    "papa",
    "plátano",
    "pollo",
    "quequisque",
    "queso",
    "sorgo",
    "soya",
    "verdura",
    "yuca",
    "espárrago",
    "aguacate",
    "albahaca",
    "brócoli",
    "mantequilla",
    "clementinas",
    "chile",
    "leche de coco",
    "café - polvo",
    "cuscús",
    "crema - fraiche",
    "dip",
    "polvo de hornear",
    "harina para todo uso",
    "pasas",
    "azúcar blanco",
    "yemas de huevo",
    "almidón de maíz",
    "crema de tártaro",
    "obleas de vainilla",
    "extracto",
    "nueces tostadas",
    "claras",
    "ron ligero",
    "salchichas",
    "bulbo de hinojo",
    "frondas",
    "aceite de oliva",
    "pimientos cubanos",
    "cebollas",
    "cortes de carne",
    "filete",
    "salchicha ahumada",
    "okra",
    "camarones"
];
