export const pathologies = [
    "Trastorno de coagulación",
    "Demencia / Alzheimer",
    "Desorden Gastrointestinal",
    "Enfermedad cardiaca",
    "Altos niveles de colesterol",
    "Hipertensión",
    "Enfermedades del Riñón",
    "Enfermedades Respiratorias",
    "Trastorno psicológico",
    "Stroke ",
    "Apoplejia (derrame)/ Ataque Cerebral",
    "Sudden  ",
    "Síndrome de Muerte Súbita Infantil",
    "Enfermedad desconocida",
    "Colesterol alto",
    "Enfermedad pulmonar",
    "Demencia /Degenerative (Alzheimer)",
    "Osteoporosis",
    "Septicemia",
    "Apoplejia (derrame)/Ataque Cerebral",
    "Diabetes tipo 1",
    "Diabetes tipo 2",
    "Diabetes gestacional",
    "Diabetes",
    "Ansiedad",
    "Trastorno por déficit de atención con hiperactividad",
    "Autismo",
    "Trastorno Bipolar",
    "Demencia",
    "Depresión",
    "Transtorno Alimenticio",
    "Trastorno Obsesivo Compulsivo",
    "Trastorno de Pánico",
    "Trastorno de la personalidad",
    "Trastorno de estrés postraumático",
    "Esquizofrenia",
    "Fobia social",
    "No especificado",
    "Asma",
    "Bronquitis crónica",
    "Enfermedades Crónicas respiratorio inferior",
    "EPOC (Enfermedades Pulmonares Obstructivas Crónicas",
    "Enfisema",
    "Gripe / Neumonía",
    "Enfermedad renal quística",
    "Enfermedad Renal Diabética",
    "Nefritis",
    "Nefrosis de riñón",
    "Síndrome nefrótico",
    "Enfermedad renal presente desde el nacimiento",
    "Cáncer de los huesos",
    "Cáncer de mama",
    "Cáncer de colon",
    "Cáncer de esófago (Esofágico)",
    "Cáncer gástrico",
    "Cáncer de riñón",
    "Leucemia",
    "Cáncer de pulmón",
    "Cáncer de pulmón",
    "Cáncer del músculo",
    "Cáncer de ovario",
    "Cáncer de próstata",
    "Cáncer de piel",
    "Cáncer de tiroides",
    "Cáncer uterino",
    "Cáncer de páncreas",
    "Cáncer de hígado",
    "Cáncer de cerebro",
    "Cáncer de cerebro",
    "Cáncer colorrectal",
    "Cáncer rectal",
    "Poliposis adnenomatous familiar (PAF)",
    "Pólipos de colon",
    "Enfermedad de Crohn",
    "Síndrome del Intestino Irritable",
    "Colitis Ulcerosa",
    "Desorden Gastrointestinal",
    "Enfermedad del corazón",
    "Ataque cardiaco",
    "Enfermedad de las Arterias Coronarias",
    "Angina",
    "Trombosis Venosa Profunda (TVP)",
    "Embolia pulmonar",
    "Trastorno de coagulación",
    "Deterioro de la glucosa en ayunas",
    "Deterioro de la glucosa en ayunas",
    "La tolerancia a la glucosa",
    "Resistencia a la insulina",
    "Resistencia a la insulina",
    "Diabetes mellitus en el inicio de la madurez (MODY)",
    "Diabetes mellitus en el inicio de la madurez (MODY)",
    "Trastorno Mental",
    "Enfermedad desconocida",
    "Pre-diabetes",
  
    "Cáncer Desconocido",
    "Trastorno de coagulación Desconocido",
    "Diabetes Desconocida",
    "Desorden Gastrointestinal Desconocido",
    "Cardiopatía Desconocida",
    "Enfermedades renales Desconocidas",
    "Enfermedades Respiratorias Desconocidas",
    "Trastorno psicológico Desconocido",
    "Enfermedad Desconocida",
  ];